server.port=${PORT:8080}

# ??????100%????
spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:47842/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=FbyXeVnCPLalLWEdcIReqoSjfgmtdqYm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.booksysytem