spring.application.name=BookSysytem
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/book_system?serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456

mybatis.type-aliases-package=com.example.booksysytem.entity
mybatis.mapper-locations=classpath:mapper/*.xml

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html